name: build .Net and Typescript

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    # .net ci/cd

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'ga'

    - name: Restore .NET dependencies
      run: dotnet restore CSharp/aoc2023.csproj

    - name: Build .NET
      run: dotnet build CSharp/aoc2023.csproj --no-restore --configuration Release

    - name: Test .NET
      run: dotnet test CSharp/aoc2023.csproj --no-build --verbosity normal --configuration Release


    # typescript ci/cd

    - name: Setup Typescript
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Node and Typescript dependencies
      run: npm ci

    - name: Run all Typescript tests
      run: npm test
