name: build .Net and Typescript

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'ga'

    - name: Restore .NET dependencies
      run: dotnet restore CSharp/aoc2023.csproj

    - name: Build .NET
      run: dotnet build CSharp/aoc2023.csproj --no-restore --configuration Release

    - name: Test .NET
      run: dotnet test CSharp/aoc2023.csproj --no-build --verbosity normal --configuration Release

    # - name: Setup Typescript
       # uses: actions/setup-???@v?
